name: ryandavisphoto
favicon: null
layout_spectrum: 0.0197014263831079
typography_spectrum: 0.3424473151098937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1579534017946571
  lightness: 0.8195934451650828
  saturation: 0.07225078670307994
  rhythmicContrast: 0.8995859175920486
purpose: []
